### ISSUE TITLE
error when response is without body  : /rest/v1/activities/pagingtoken.json

### ISSUE THREAD

**Issue by surajkb74** [SpeakData/minimarketo#2]
Does it support getpagingtoken in which there is no response.
i'm getting error --->
No body! Check URL: https://XYZ.mktorest.com/rest/v1/activities/pagingtoken.jsonsinceDatetime=2007-07-01T13%3A00%3A00Z

**Comment by ghiden** [comment]
Please read error message. It says "Check URL"
It's missing "?".
```
https://XYZ.mktorest.com/rest/v1/activities/pagingtoken.json?sinceDatetime=2007-07-01T13%3A00%3A00Z
```

I would suggest having a function like this:
```
func pagingToken(since string) string {
	return fmt.Sprintf("/activities/pagingtoken.json?sinceDatetime=%s", since)
}
```

**Comment by surajkb74** [comment]
Once again thank you. It's worked. You can close the issue.

Our requirement is to mirror Marketo lead database into our local database.
Need to make calls in a loop until we retrieve all records.
